### PR TITLE
Publish AWS Scripts

### PR DESCRIPTION
**Pull request by dcbroad3**

### CODE REVIEW

**Comment by cholzmer** [comment]
@dcbroad3, We are missing the file 'PIDA_Scripts.zip' under scripts/PIDA/

**Comment by cholzmer** [comment]
> 
> 
> @dcbroad3, We are missing the file 'PIDA_Scripts.zip' under scripts/PIDA/

I see the issue now. In the global .gitignore there is a rule for *.zip. We'll need to add a flag for our AWS subfolder.

**Review by cholzmer — CHANGES_REQUESTED** [review]
Modify .gitignore so we are not excluding 'PIDA_Scripts.zip' under scripts/PIDA

**Comment by dcbroad3** [comment]
> 
> 
> Modify .gitignore so we are not excluding 'PIDA_Scripts.zip' under scripts/PIDA

@cholzmer This should be fixed now, let me know if you still see anything missing.

**Comment by cholzmer** [comment]
@dcbroad3, yep the files look good now. Thanks.

**Review by cholzmer — APPROVED** [review]
Final round of testing done. Confirmed successful automated deployment of both HA and nonHA PI System Deployment Samples through Azure DevOps build pipelines.

**Comment by derekendres** [comment]
we should update the outside readme with the links to these

**Comment by cholzmer** [comment]
> 
> 
> we should update the outside readme with the links to these
@derekendres , Sounds good.

 
@dcbroad3, I will update the readme within Azure DevOps and then give you a copy of the new readme to update GitHub.

**Comment by derekendres** [comment]
the details link in the scripts readme for azure takes you to AWS

**Comment by dcbroad3** [comment]
> 
> 
> the details link in the scripts readme for azure takes you to AWS

Fixed this.

**Pull request closed without merging**
