### PR TITLE
npm audit fix and npm update

### PR DESCRIPTION
**Pull request by elam-osi**
Ran `npm audit fix` and `npm update` to fix vulnerabilities and fix warnings about packages being out of date.

### CODE REVIEW

**Comment by derekendres** [comment]
Apologies for all of the azure-pipeline comments and calls to it.  i was trying to get the test to run and it was a pipeline issue since this is coming in from a fork.  There was another issue with getting it setup so it took a couple extra calls to the bot...  but now this should be running as expected.  @elam-osi  it looks like it isn't passing these the test (or building with ng build)

**Comment by elam-osi** [comment]
@derekendres I've made a couple of updates to address the build errors. How should I trigger another PR build?

**Comment by derekendres** [comment]
> @derekendres I've made a couple of updates to address the build errors. How should I trigger another PR build?

a codeowner must kick it off so i just did

**Review by derekendres — APPROVED** [review]

**Review by dcbroad3 — APPROVED** [review]

**Pull request merged**
